name: coreplugin

on:
  push:
    branches: [ scarthgap ]
  pull_request:
    branches: [ scarthgap ]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: install prerequisites
      run: |
        sudo apt-get -q update
        sudo apt-get install automake
        sudo apt-get install git
        sudo apt-get install build-essential
        sudo apt-get install gettext
    - name: compile coreplugin python
      run: |
        python -m compileall .
        find . -type f -name "*.po" -exec msgfmt {} -o {}.mo \;
        echo done!
