name: ovbot

on:
  push:
    branches: [ scarthgap ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:

      - uses: actions/checkout@v2
        with:
          ref: 'scarthgap'

      - uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Build python 3.12
        run: |
          sudo apt-get -q update
          sudo apt-get install dos2unix
          pip install --upgrade pip autopep8 future
          ./CI/build.sh
